debug: true

database:
  type: SQLite
  username: xxx
  password: xxx
  url: xxx

bot:
  token: XXX
  # form / command / both
  getType: "both"
  form:
    embedSent: false
    channelID: XXX
    formTitle: "Nadaj rangƒô | SURVIVAL"
    formID: "getRoleSurvival"
    multiLineButtons: false
    # Primary / Success / Secondary / Destructive
    buttonStyle: Secondary
    embed:
      title: "Nadaj rangƒô!"
      desc: "Nadaj sobie rangƒô klikajƒÖc poni≈ºszy przycisk\n**:)**"
      color: "#1953bf"
      buttonID: "getRoleSurvival"
      buttonText: "Nadaj rangƒô"
      buttonEmoji: "üê∫"

  command:
    name: "giverank"
    description: "Uzyskaj rangƒô z serwera"
    commandOptions:
      NICK:
        name: "nick"
        desc: "Tw√≥j nick Minecraft"
      CODE:
        name: "kod"
        desc: "Tw√≥j kod z /dcGetCode"

  logEmbed:
    channelID: XXX
    title: "Odebrano rangƒô! **SURVIVAL**"
    desc: "**Nick:** {NICK}\n
           **Ranga:** {ROLE}\n
           **Discord:** {DISCORD}"
    color: "#1953bf"

roles:
  VIP:
    id:
      - 1073344115191844956

commands:
  RELOAD:
    name: dcreload
    permission: dcr.reload
  GETCODE:
    name: dcgetcode
    self:
      permission: dcr.getcode.self
    permission: dcr.getcode.other
  MANAGEUSER:
    name: dcmanage
    permission: dcr.manageuser